In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('feature_engineer_df.csv', index_col = 'id')

In [3]:
test_df = pd.read_csv('feature_engineer_test.csv', index_col='id')

In [4]:
df.sample(10)

,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format,total_sales,relative_category_price,relative_product_price
id,,,,,,,,,,,,,,
row_04482,PRD-G5MMQ7,10.449,Regular,0.0634,Breakfast,178.62,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,2703.44,1.109324,1.028650
row_07158,PRD-LCSXU1,11.657,Regular,0.0570,Baking Goods,166.98,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,5716.91,1.325009,0.970733
row_06839,PRD-25KFBO,19.663,Regular,0.0250,Fruits And Vegetables,144.15,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,1679.10,1.032789,0.984107
row_06953,PRD-UBXCU2,8.976,Low Fat,0.0188,Household,170.34,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,2400.64,1.140007,1.003925
row_01000,PRD-YCKVJK,13.255,Regular,0.1916,Canned,219.26,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,3068.13,1.604949,1.037181
row_07834,PRD-NSQDTZ,17.637,Low Fat,0.0511,Snack Foods,112.16,STORE-DKU,30,Medium,Tier_2,Standard Supermarket,1926.28,0.791469,0.975545
row_00956,PRD-SVH3EJ,6.292,Low Fat,0.0128,Meat,39.55,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,1101.33,0.296762,1.005923
row_07244,PRD-XLTA8I,13.066,Low Fat,0.0559,Soft Drinks,140.41,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,871.10,1.198436,0.990815
row_07815,PRD-2WLNC8,8.750,Low Fat,0.0162,Household,198.15,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,4181.55,1.320051,1.001276
row_04224,PRD-EI7XZU,13.191,Low Fat,0.0209,Fruits And Vegetables,179.56,STORE-HL7,23,Medium,Tier_3,Superstore,2243.25,1.285666,0.994544

In [5]:
import numpy as np
df['average_tp/category'] = df.groupby(['product_category'])['total_sales'].transform('mean')
df['average_store_tp/category'] = df.groupby(['product_category', 'store_code'])['total_sales'].transform('mean')
group = df.groupby(['product_category', 'store_code'])['total_sales']
df['store_tp/category_SE'] = group.transform('std') / np.sqrt(group.transform('count'))

df['average_tp/product'] = df.groupby(['product_code'])['total_sales'].transform('mean')

In [6]:
# Category-level average
average_tp_category = (
    df.groupby('product_category')['total_sales']
      .mean()
)

test_df['average_tp/category'] = (
    test_df['product_category'].map(average_tp_category)
)


average_tp_product = (
    df.groupby('product_code')['total_sales']
      .mean()
)

test_df['average_tp/product'] = (
    test_df['product_code'].map(average_tp_product)
)

# Store × category average
group = df.groupby(
    ['product_category', 'store_code']
)['total_sales']

average_store_tp_category = group.mean()

test_df['average_store_tp/category'] = (
    test_df.set_index(
        ['product_category', 'store_code']
    ).index.map(average_store_tp_category)
)


# Store × category standard error
store_tp_category_SE = (
    group.std() / np.sqrt(group.count())
)

test_df['store_tp/category_SE'] = (
    test_df.set_index(
        ['product_category', 'store_code']
    ).index.map(store_tp_category_SE)
)

In [7]:
test_df.sample(10)

,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format,relative_category_price,relative_product_price,average_tp/category,average_tp/product,average_store_tp/category,store_tp/category_SE
id,,,,,,,,,,,,,,,,,
row_02393,PRD-E6VA05,9.611,Low Fat,0.0418,Soft Drinks,32.98,STORE-9RG,28,Small,Tier_2,Standard Supermarket,0.295633,1.009180,1775.278672,559.533333,1904.723250,193.671389
row_06552,PRD-1LWNLR,11.615,Low Fat,0.0000,Baking Goods,245.17,STORE-DKU,30,Medium,Tier_2,Standard Supermarket,1.729058,1.000000,1884.227196,2748.994000,2101.041091,178.111618
row_04945,PRD-S57TCO,5.336,Regular,0.0000,Baking Goods,128.33,STORE-YLW,35,Small,Tier_1,Standard Supermarket,1.316465,0.990353,1884.227196,1756.894000,2357.200952,200.798663
row_02621,PRD-F3G3T3,15.611,Low Fat,0.0314,Snack Foods,232.74,STORE-JOR,34,Small,Tier_3,Corner Shop,1.559521,1.000000,2139.892734,3843.292000,383.701800,34.915851
row_02884,PRD-J5S6R0,18.043,Regular,0.0452,Dairy,144.86,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,0.868729,0.998002,2086.221741,2426.727500,2225.142222,165.897015
row_06647,PRD-08S1A7,11.285,Low Fat,0.0745,Fruits And Vegetables,189.41,STORE-YLW,35,Small,Tier_1,Standard Supermarket,1.197032,0.986048,2110.826544,2791.705000,2400.278155,138.683304
row_07746,PRD-S9CFU5,9.177,Regular,0.1129,Snack Foods,161.67,STORE-YLW,35,Small,Tier_1,Standard Supermarket,1.133431,1.003829,2139.892734,1587.390000,2321.719681,133.660230
row_06279,PRD-J0KX9K,9.768,Low Fat,0.1116,Fruits And Vegetables,170.66,STORE-DKU,30,Medium,Tier_2,Standard Supermarket,1.204088,1.000000,2110.826544,2035.520000,2218.528750,138.681799
row_00733,PRD-Y0VDVE,16.054,Low Fat,0.0470,Dairy,237.11,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,1.574958,0.999621,2086.221741,1830.283333,3236.615435,240.249878
row_04139,PRD-VG0CH2,12.384,Regular,0.0616,Frozen Foods,105.23,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,0.746589,1.000000,2008.810258,1937.747500,2206.898000,197.000627

In [8]:
df.sample(10)

,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format,total_sales,relative_category_price,relative_product_price,average_tp/category,average_store_tp/category,store_tp/category_SE,average_tp/product
id,,,,,,,,,,,,,,,,,,
row_00147,PRD-ZN1N5R,12.0060,Regular,0.0335,Meat,198.96,STORE-9RG,28,Small,Tier_2,Standard Supermarket,3195.63,1.327866,1.008116,2132.197190,2463.850256,223.062346,3528.491667
row_03798,PRD-BHKJ25,20.6310,Low Fat,0.1141,Baking Goods,105.19,STORE-9RG,28,Small,Tier_2,Standard Supermarket,991.02,0.880102,0.989986,1884.227196,1749.200741,176.100182,771.734000
row_04489,PRD-HD96M8,12.0440,Low Fat,0.0633,Starchy Foods,35.32,STORE-HL7,23,Medium,Tier_3,Superstore,258.07,0.221974,0.969664,2284.124364,2122.018571,347.978297,575.882500
row_02345,PRD-8INI8M,6.6365,Regular,0.1183,Snack Foods,89.81,STORE-YLW,35,Small,Tier_1,Standard Supermarket,2376.98,0.624323,1.012229,2139.892734,2321.719681,133.660230,1563.003750
row_06548,PRD-MSND8D,9.0270,Low Fat,0.0398,Soft Drinks,36.66,STORE-AGY,45,Large,Tier_3,Standard Supermarket,1062.37,0.330886,1.008695,1775.278672,1908.891176,209.410663,768.744000
row_04543,PRD-3KI24S,17.7100,Low Fat,0.0149,Household,179.65,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,4948.13,1.289147,0.987815,2186.078251,3333.886301,195.710125,2852.558000
row_03507,PRD-EMDJNI,15.8800,Low Fat,0.0214,Household,43.47,STORE-YLW,35,Small,Tier_1,Standard Supermarket,445.55,0.286709,0.995420,2186.078251,2220.656023,151.760174,514.650000
row_05762,PRD-0T2RJM,7.7610,Low Fat,0.0330,Canned,114.02,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,2603.76,0.834609,0.991340,2105.576102,2475.600508,190.564630,1628.142000
row_00384,PRD-ZN1N5R,12.1430,Regular,0.0349,Meat,198.69,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,3109.67,1.490864,1.006747,2132.197190,2157.676571,252.135929,3528.491667
row_03393,PRD-RWWK6P,8.1050,Low Fat,0.0136,Baking Goods,95.46,STORE-YLW,35,Small,Tier_1,Standard Supermarket,2238.28,0.731291,1.010747,1884.227196,2357.200952,200.798663,1408.342500

In [9]:
X_train = df.drop(columns=['total_sales', 'fat_content']).copy()
y_train = df['total_sales'].copy()

X_test = test_df.drop(columns=['fat_content']).copy()

In [10]:
from catboost import CatBoostRegressor
from sklearn.model_selection import KFold, cross_val_score
import numpy as np

categorical_features = [
    'product_code',
    'product_category',
    'store_code',
    'store_size',
    'store_location_tier',
    'store_format'
]

model = CatBoostRegressor(
    iterations=500,
    learning_rate=0.02,
    early_stopping_rounds=100,
    depth=6,
    loss_function='RMSE',
    random_seed=62,
    verbose=0
)

kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = []

for train_index, validation_index in kf.split(X_train):

    X_fold_train = X_train.iloc[train_index]
    X_fold_valid = X_train.iloc[validation_index]

    y_fold_train = y_train.iloc[train_index]
    y_fold_valid = y_train.iloc[validation_index]

    model.fit(
        X_fold_train,
        y_fold_train,
        cat_features=categorical_features
    )

    predictions = model.predict(X_fold_valid)

    rmse = np.sqrt(np.mean((y_fold_valid - predictions) ** 2))

    scores.append(rmse)

    print(f"Fold RMSE: {rmse:.4f}")

print("\nCross-validation results")
print(f"RMSE scores: {scores}")
print(f"Mean RMSE: {np.mean(scores):.4f}")
print(f"Std RMSE: {np.std(scores):.4f}")

Fold RMSE: 791.3093
Fold RMSE: 827.3086
Fold RMSE: 842.2890
Fold RMSE: 816.7915
Fold RMSE: 843.6795

Cross-validation results
RMSE scores: [np.float64(791.3093383890297), np.float64(827.3085593866413), np.float64(842.2890273210567), np.float64(816.7914639219747), np.float64(843.6795078615861)]
Mean RMSE: 824.2756
Std RMSE: 19.2509

In [11]:
final_model = CatBoostRegressor(
    iterations=500,
    learning_rate=0.02,
    early_stopping_rounds=100,
    depth=6,
    loss_function='RMSE',
    random_seed=62,
    verbose=100
)

final_model.fit(
    X_train,
    y_train,
    cat_features=categorical_features
)

y_pred = final_model.predict(X_test)

submission_df = pd.DataFrame({
    'id': test_df.index,
    'total_sales': y_pred
})
submission_df.to_csv('submission_cv_v12_1.csv', index=False)

0:	learn: 1491.7229530	total: 100ms	remaining: 50s
100:	learn: 877.2923531	total: 5.15s	remaining: 20.4s
200:	learn: 825.5682156	total: 10.4s	remaining: 15.4s
300:	learn: 812.5075519	total: 15.1s	remaining: 10s
400:	learn: 803.0058829	total: 20.7s	remaining: 5.12s
499:	learn: 795.4869245	total: 27.2s	remaining: 0us

In [19]:
df['average_tp/product'] = df.groupby(['product_code'])['total_sales'].transform('mean')
df['average_store_tp/product'] = df.groupby(['product_code'])['total_sales'].transform('mean')
group = df.groupby(['product_code'])['total_sales']
df['store_tp/product_SE'] = group.transform('std') / np.sqrt(group.transform('count'))

In [20]:
df.sample(10)

,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format,total_sales,relative_category_price,relative_product_price,average_tp/category,average_store_tp/category,store_tp/category_SE,average_tp/product,average_store_tp/product,store_tp/product_SE
id,,,,,,,,,,,,,,,,,,,,
row_07811,PRD-AN63XD,13.311000,Low Fat,0.0062,Frozen Foods,193.36,STORE-9RG,28,Small,Tier_2,Standard Supermarket,4216.62,1.324424,1.024587,2008.810258,2446.437183,181.820593,2123.710000,2123.710000,1125.359257
row_00539,PRD-VG9YSQ,12.973000,Regular,0.1022,Frozen Foods,200.87,STORE-HL7,23,Medium,Tier_3,Superstore,3027.56,1.390760,1.008839,2008.810258,2011.307722,163.834052,3644.010000,3644.010000,616.450000
row_01652,PRD-HDPJSA,6.390400,Low Fat,0.2276,Canned,259.97,STORE-T5G,47,Small,Tier_1,Corner Shop,1381.45,1.923034,0.995526,2105.576102,433.118387,59.787606,2393.596667,2393.596667,770.684273
row_02476,PRD-JRFCO7,9.377000,Low Fat,0.1171,Frozen Foods,60.18,STORE-HL7,23,Medium,Tier_3,Superstore,964.34,0.416667,1.023295,2008.810258,2011.307722,163.834052,1213.643333,1213.643333,310.914459
row_07997,PRD-EGKRHJ,5.429000,Regular,0.0058,Snack Foods,99.57,STORE-AGY,45,Large,Tier_3,Standard Supermarket,1686.42,0.687337,0.996657,2139.892734,2345.208627,138.376641,1740.258000,1740.258000,135.366141
row_06642,PRD-L6H2NL,8.949000,Low Fat,0.0796,Household,46.88,STORE-HL7,23,Medium,Tier_3,Superstore,463.40,0.322639,0.983263,2186.078251,2000.701096,153.404093,389.234000,389.234000,142.726963
row_08485,PRD-PLCL5F,18.626667,Low Fat,0.0255,Baking Goods,125.23,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,3529.07,0.993717,0.998764,1884.227196,3078.721273,209.643604,2417.905000,2417.905000,777.910588
row_03821,PRD-N5SYDV,5.343000,Low Fat,0.0112,Household,259.88,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,4385.85,1.739257,0.991511,2186.078251,2353.361585,140.781499,3561.805000,3561.805000,824.045000
row_08484,PRD-20AP4V,19.604333,Low Fat,0.0250,Household,102.25,STORE-AGY,45,Large,Tier_3,Standard Supermarket,710.90,0.697771,0.974032,2186.078251,2319.673704,168.131233,1517.752000,1517.752000,448.574816
row_04083,PRD-WOSQMC,16.632000,Low Fat,0.0426,Fruits And Vegetables,181.62,STORE-AGY,45,Large,Tier_3,Standard Supermarket,1662.65,1.307007,1.000441,2110.826544,2145.838167,127.001779,1857.540000,1857.540000,194.890000

In [24]:
df[df['store_tp/product_SE'].isna()]

,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format,total_sales,relative_category_price,relative_product_price,average_tp/category,average_store_tp/category,store_tp/category_SE,average_tp/product,average_store_tp/product,store_tp/product_SE
id,,,,,,,,,,,,,,,,,,,,
row_00021,PRD-2CQ23Q,7.746000,Low Fat,0.0297,Canned,167.19,STORE-AGY,45,Large,Tier_3,Standard Supermarket,1774.73,1.317876,1.0,2105.576102,2119.081522,208.528384,1774.73,1774.73,NaN
row_00199,PRD-4RZCNO,6.192000,Low Fat,0.0283,Household,112.17,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,1277.51,0.750702,1.0,2186.078251,2353.361585,140.781499,1277.51,1277.51,NaN
row_00282,PRD-J8GI5O,5.991000,Regular,0.1054,Frozen Foods,217.00,STORE-HL7,23,Medium,Tier_3,Superstore,1466.60,1.502440,1.0,2008.810258,2011.307722,163.834052,1466.60,1466.60,NaN
row_00379,PRD-7JH2LK,13.359873,Low Fat,0.0762,Snack Foods,120.25,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,4318.68,0.859220,1.0,2139.892734,3373.825408,164.308756,4318.68,4318.68,NaN
row_00576,PRD-U9G2LT,7.694000,Regular,0.0680,Snack Foods,56.45,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,1312.30,0.380384,1.0,2139.892734,2417.257353,146.520012,1312.30,1312.30,NaN
row_00648,PRD-ZYK421,9.157000,Low Fat,0.0669,Household,33.10,STORE-JOR,34,Small,Tier_3,Corner Shop,34.79,0.226579,1.0,2186.078251,393.564821,42.614923,34.79,34.79,NaN
row_00890,PRD-VD6XDH,20.624000,Low Fat,0.1158,Snack Foods,169.85,STORE-JOR,34,Small,Tier_3,Corner Shop,541.36,1.126340,1.0,2139.892734,383.701800,34.915851,541.36,541.36,NaN
row_00938,PRD-1AS2YU,18.776000,Low Fat,0.0897,Baking Goods,134.25,STORE-JOR,34,Small,Tier_3,Corner Shop,262.69,1.080266,1.0,1884.227196,247.706316,29.478983,262.69,262.69,NaN
row_01241,PRD-MRKSQJ,13.359873,Regular,0.1286,Snack Foods,95.05,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,2362.83,0.679159,1.0,2139.892734,3373.825408,164.308756,2362.83,2362.83,NaN
row_01367,PRD-Q8DDGB,8.392000,Regular,0.0351,Frozen Foods,75.71,STORE-YLW,35,Small,Tier_1,Standard Supermarket,1595.19,0.588452,1.0,2008.810258,2065.102750,148.920686,1595.19,1595.19,NaN
row_01437,PRD-YHREVB,5.498000,Low Fat,0.0473,Health And Hygiene,167.84,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,2191.66,1.260390,1.0,1900.160346,2056.572857,161.525193,2191.66,2191.66,NaN
row_01710,PRD-NBDVPI,13.960916,Regular,0.0980,Fruits And Vegetables,221.50,STORE-T5G,47,Small,Tier_1,Corner Shop,447.61,1.565529,1.0,2110.826544,335.275345,26.921081,447.61,447.61,NaN
row_01898,PRD-K8PK3Y,18.125000,Low Fat,0.0237,Soft Drinks,153.93,STORE-HL7,23,Medium,Tier_3,Superstore,2821.55,1.156838,1.0,1775.278672,1844.150250,232.811025,2821.55,2821.55,NaN
row_01904,PRD-0LMI8X,7.731000,Regular,0.0564,Canned,125.26,STORE-HL7,23,Medium,Tier_3,Superstore,2462.31,0.943404,1.0,2105.576102,1668.945000,129.538424,2462.31,2462.31,NaN
row_01969,PRD-KMIQD4,17.547000,Low Fat,0.0179,Starchy Foods,181.91,STORE-HL7,23,Medium,Tier_3,Superstore,3298.79,1.143241,1.0,2284.124364,2122.018571,347.978297,3298.79,3298.79,NaN
row_02000,PRD-QIGCT2,12.601278,Regular,0.0553,Baking Goods,121.63,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,3438.29,0.965150,1.0,1884.227196,3078.721273,209.643604,3438.29,3438.29,NaN
row_02425,PRD-AZUAYN,10.088000,Low Fat,0.1226,Health And Hygiene,156.63,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,2545.46,1.176209,1.0,1900.160346,2056.572857,161.525193,2545.46,2545.46,NaN
row_02548,PRD-0UQYHD,16.106000,Low Fat,0.0000,Household,115.27,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,3229.81,0.771449,1.0,2186.078251,2353.361585,140.781499,3229.81,3229.81,NaN
row_02564,PRD-FZTVOV,8.587000,Low Fat,0.0725,Snack Foods,203.22,STORE-AGY,45,Large,Tier_3,Standard Supermarket,2040.07,1.402839,1.0,2139.892734,2345.208627,138.376641,2040.07,2040.07,NaN
row_02638,PRD-07NNDG,10.080000,Regular,0.0477,Frozen Foods,261.47,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,3976.81,1.877020,1.0,2008.810258,2206.898000,197.000627,3976.81,3976.81,NaN
row_02693,PRD-GHO6AC,7.796000,Regular,0.0679,Snack Foods,95.53,STORE-YLW,35,Small,Tier_1,Standard Supermarket,1559.66,0.664086,1.0,2139.892734,2321.719681,133.660230,1559.66,1559.66,NaN
row_02826,PRD-8L4EBE,12.874000,Regular,0.0616,Baking Goods,205.05,STORE-YLW,35,Small,Tier_1,Standard Supermarket,579.21,1.570829,1.0,1884.227196,2357.200952,200.798663,579.21,579.21,NaN
row_03078,PRD-0JE4QV,6.763000,Low Fat,0.0000,Frozen Foods,218.87,STORE-YLW,35,Small,Tier_1,Standard Supermarket,3007.58,1.701157,1.0,2008.810258,2065.102750,148.920686,3007.58,3007.58,NaN
row_03712,PRD-WKI85L,13.472000,Low Fat,0.0000,Snack Foods,62.67,STORE-JOR,34,Small,Tier_3,Corner Shop,60.59,0.415589,1.0,2139.892734,383.701800,34.915851,60.59,60.59,NaN
row_04043,PRD-M80O2R,11.758637,Low Fat,0.0835,Soft Drinks,193.31,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,575.13,1.781389,1.0,1775.278672,2594.794412,251.169996,575.13,575.13,NaN
row_04064,PRD-2XAHHF,20.179000,Low Fat,0.0251,Health And Hygiene,142.22,STORE-JOR,34,Small,Tier_3,Corner Shop,591.54,1.111597,1.0,1900.160346,361.429200,64.482332,591.54,591.54,NaN
row_04153,PRD-FPTNK2,14.744000,Low Fat,0.0958,Fruits And Vegetables,174.54,STORE-HL7,23,Medium,Tier_3,Superstore,658.13,1.249723,1.0,2110.826544,1867.946937,124.103562,658.13,658.13,NaN
row_04402,PRD-86HF4I,15.411000,Low Fat,0.0000,Meat,262.17,STORE-JOR,34,Small,Tier_3,Corner Shop,1289.07,1.938438,1.0,2132.197190,413.267692,73.233739,1289.07,1289.07,NaN
row_04481,PRD-QNVF2X,14.491000,Regular,0.0188,Dairy,265.31,STORE-YLW,35,Small,Tier_1,Standard Supermarket,5011.59,1.848448,1.0,2086.221741,2137.230152,182.640085,5011.59,5011.59,NaN
row_04583,PRD-8CL0LC,13.057765,Low Fat,0.0453,Canned,161.63,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,4423.86,1.217983,1.0,2105.576102,3328.548679,202.770571,4423.86,4423.86,NaN
row_04640,PRD-IQK291,10.715000,Low Fat,0.0188,Soft Drinks,192.05,STORE-9RG,28,Small,Tier_2,Standard Supermarket,2346.92,1.430015,1.0,1775.278672,1904.723250,193.671389,2346.92,2346.92,NaN
row_04735,PRD-PZFBNK,6.510000,Low Fat,0.0783,Starchy Foods,197.28,STORE-YLW,35,Small,Tier_1,Standard Supermarket,3946.49,1.402903,1.0,2284.124364,2293.247273,417.192364,3946.49,3946.49,NaN
row_04998,PRD-K1Z5BY,11.228000,Low Fat,0.0429,Snack Foods,175.78,STORE-YLW,35,Small,Tier_1,Standard Supermarket,2017.35,1.221951,1.0,2139.892734,2321.719681,133.660230,2017.35,2017.35,NaN
row_05111,PRD-LV9PLM,6.886000,Low Fat,0.0963,Health And Hygiene,260.34,STORE-JOR,34,Small,Tier_3,Corner Shop,255.29,2.034828,1.0,1900.160346,361.429200,64.482332,255.29,255.29,NaN
row_05206,PRD-7DMS2Z,13.187000,Low Fat,0.0328,Meat,61.79,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,748.04,0.459089,1.0,2132.197190,2450.358000,235.827617,748.04,748.04,NaN
row_05363,PRD-DQHDK3,12.977197,Regular,0.0642,Snack Foods,113.44,STORE-T5G,47,Small,Tier_1,Corner Shop,697.49,0.805248,1.0,2139.892734,337.253492,32.132329,697.49,697.49,NaN
row_05519,PRD-OGHEXC,10.914000,Low Fat,0.0576,Health And Hygiene,102.55,STORE-9RG,28,Small,Tier_2,Standard Supermarket,1444.10,0.835533,1.0,1900.160346,2223.808372,209.756536,1444.10,1444.10,NaN
row_05821,PRD-DH3TKZ,13.946506,Regular,0.0302,Dairy,88.47,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,3369.39,0.644381,1.0,2086.221741,3236.615435,240.249878,3369.39,3369.39,NaN
row_06211,PRD-UCR0F5,20.194000,Regular,0.0820,Breads,168.57,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,1838.71,1.185985,1.0,2084.382537,1897.417143,367.210467,1838.71,1838.71,NaN
row_06286,PRD-JQPKAH,8.708000,Low Fat,0.0702,Household,93.28,STORE-YLW,35,Small,Tier_1,Standard Supermarket,1913.85,0.615233,1.0,2186.078251,2220.656023,151.760174,1913.85,1913.85,NaN
row_06341,PRD-BCDPQ9,13.997000,Regular,0.1987,Dairy,232.32,STORE-T5G,47,Small,Tier_1,Corner Shop,466.15,1.708615,1.0,2086.221741,318.071220,38.744997,466.15,466.15,NaN
row_06704,PRD-GILBRO,6.748000,Low Fat,0.0224,Meat,147.08,STORE-AGY,45,Large,Tier_3,Standard Supermarket,2604.15,1.073675,1.0,2132.197190,2395.685143,259.787550,2604.15,2604.15,NaN
row_06827,PRD-X9X39I,10.030000,Low Fat,0.1047,Snack Foods,112.66,STORE-HL7,23,Medium,Tier_3,Superstore,3480.32,0.783095,1.0,2139.892734,1915.991313,114.929921,3480.32,3480.32,NaN
row_06934,PRD-DH02YH,10.101000,Low Fat,0.0000,Fruits And Vegetables,252.45,STORE-HL7,23,Medium,Tier_3,Superstore,3224.66,1.807566,1.0,2110.826544,1867.946937,124.103562,3224.66,3224.66,NaN
row_07011,PRD-7SGMSO,19.778000,Low Fat,0.0402,Hard Drinks,123.74,STORE-9RG,28,Small,Tier_2,Standard Supermarket,780.82,0.894954,1.0,2065.850182,2085.614118,258.674649,780.82,780.82,NaN
row_07398,PRD-Z45QF8,9.616000,Low Fat,0.0512,Snack Foods,259.90,STORE-DKU,30,Medium,Tier_2,Standard Supermarket,4905.81,1.834012,1.0,2139.892734,2032.136667,127.727861,4905.81,4905.81,NaN
row_07432,PRD-AQYP2R,19.188000,Regular,0.0159,Canned,188.99,STORE-9RG,28,Small,Tier_2,Standard Supermarket,3437.97,1.287989,1.0,2105.576102,2467.126613,180.298824,3437.97,3437.97,NaN
row_07553,PRD-F07UQN,5.680000,Low Fat,0.0511,Soft Drinks,188.52,STORE-DKU,30,Medium,Tier_2,Standard Supermarket,1527.38,1.535067,1.0,1775.278672,2002.704615,202.979855,1527.38,1527.38,NaN
row_07906,PRD-1KAUPO,14.367000,Low Fat,0.0888,Snack Foods,114.01,STORE-HL7,23,Medium,Tier_3,Superstore,1798.67,0.792479,1.0,2139.892734,1915.991313,114.929921,1798.67,1798.67,NaN
row_08104,PRD-EJRBVY,7.911000,Regular,0.0332,Snack Foods,163.63,STORE-HL7,23,Medium,Tier_3,Superstore,1841.84,1.137385,1.0,2139.892734,1915.991313,114.929921,1841.84,1841.84,NaN
row_08109,PRD-VFJJ50,18.999000,Regular,0.0000,Fruits And Vegetables,244.57,STORE-AGY,45,Large,Tier_3,Standard Supermarket,3431.35,1.760019,1.0,2110.826544,2145.838167,127.001779,3431.35,3431.35,NaN
row_08218,PRD-6LCP22,21.179000,Low Fat,0.0670,Canned,254.77,STORE-9RG,28,Small,Tier_2,Standard Supermarket,5170.83,1.736288,1.0,2105.576102,2467.126613,180.298824,5170.83,5170.83,NaN
row_08321,PRD-6WDG1O,9.179000,Regular,0.0482,Frozen Foods,251.81,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,1250.57,1.859022,1.0,2008.810258,2218.980000,157.262833,1250.57,1250.57,NaN
row_08429,PRD-AF3WE8,8.375000,Regular,0.1248,Frozen Foods,78.50,STORE-OYG,25,Medium,Tier_2,Standard Supermarket,1813.79,0.579537,1.0,2008.810258,2218.980000,157.262833,1813.79,1813.79,NaN
row_08432,PRD-06GUU9,12.694000,Low Fat,0.0072,Household,191.63,STORE-9RG,28,Small,Tier_2,Standard Supermarket,3802.83,1.255052,1.0,2186.078251,2628.087952,141.193033,3802.83,3802.83,NaN
row_08441,PRD-7Q5FPH,7.432000,Low Fat,0.1286,Fruits And Vegetables,163.31,STORE-DKU,30,Medium,Tier_2,Standard Supermarket,3834.43,1.152515,1.0,2110.826544,2218.528750,138.681799,3834.43,3834.43,NaN